[profile.cpu-big]
region = "eu-west-3"
image_id = "ami-051942e4055555752"
instance_type = "m6i.32xlarge"

[profile.cpu-small]
region = "eu-west-3"
image_id = "ami-051942e4055555752"
instance_type = "m6i.4xlarge"

[profile.bench]
region = "eu-west-3"
image_id = "ami-051942e4055555752"
instance_type = "m6i.metal"

[profile.bench_alt]
region = "us-east-1"
image_id = "ami-04e3bb9aebb6786df"
instance_type = "r7iz.32xlarge"

[profile.bench_alt_2]
region = "eu-west-1"
image_id = "ami-0e88d98b86aff13de"
instance_type = "hpc7a.48xlarge"

[profile.bench_alt_3]
region = "eu-west-1"
image_id = "ami-0e88d98b86aff13de"
instance_type = "hpc7a.96xlarge"

[profile.bench_alt_4]
region = "eu-west-1"
image_id = "ami-0e88d98b86aff13de"
instance_type = "m7i.48xlarge"

[command.cpu_test]
workflow = "aws_tfhe_tests.yml"
profile = "bench_alt_3"
check_run_name = "CPU AWS Tests"

[command.cpu_integer_test]
workflow = "aws_tfhe_integer_tests.yml"
profile = "bench_alt_3"
check_run_name = "CPU Integer AWS Tests"

[command.cpu_multi_bit_test]
workflow = "aws_tfhe_multi_bit_tests.yml"
profile = "bench_alt_3"
check_run_name = "CPU AWS Multi Bit Tests"

[command.cpu_wasm_test]
workflow = "aws_tfhe_wasm_tests.yml"
profile = "bench_alt_3"
check_run_name = "CPU AWS WASM Tests"

[command.cpu_fast_test]
workflow = "aws_tfhe_fast_tests.yml"
profile = "bench_alt_3"
check_run_name = "CPU AWS Fast Tests"

[command.integer_full_bench]
workflow = "integer_full_benchmark.yml"
profile = "bench_alt_4"
check_run_name = "Integer CPU AWS Benchmarks Full Suite"

[command.integer_bench]
workflow = "integer_benchmark.yml"
profile = "bench"
check_run_name = "Integer CPU AWS Benchmarks"

[command.integer_multi_bit_bench]
workflow = "integer_multi_bit_benchmark.yml"
profile = "bench"
check_run_name = "Integer multi bit CPU AWS Benchmarks"

[command.shortint_full_bench]
workflow = "shortint_full_benchmark.yml"
profile = "bench"
check_run_name = "Shortint CPU AWS Benchmarks Full Suite"

[command.shortint_bench]
workflow = "shortint_benchmark.yml"
profile = "bench"
check_run_name = "Shortint CPU AWS Benchmarks"

[command.boolean_bench]
workflow = "boolean_benchmark.yml"
profile = "bench"
check_run_name = "Boolean CPU AWS Benchmarks"

[command.pbs_bench]
workflow = "pbs_benchmark.yml"
profile = "bench_alt_3"
check_run_name = "PBS CPU AWS Benchmarks"

[command.wasm_client_bench]
workflow = "wasm_client_benchmark.yml"
profile = "cpu-small"
check_run_name = "WASM Client AWS Benchmarks"

[command.csprng_randomness_testing]
workflow = "csprng_randomness_testing.yml"
profile = "cpu-small"
check_run_name = "CSPRNG randomness testing"

[command.code_coverage]
workflow = "code_coverage.yml"
profile = "cpu-small"
check_run_name = "Code coverage"
