name: Cargo Build

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  cargo-builds:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      
      - name: Install just
        run: |
          cargo install just
      
      - name: Run pcc checks
        run: |
          just pcc

      - name: Build concrete-csprng
        run: |
          just build_concrete_csprng

      - name: Build Release core
        run: |
          just build_core AVX512_SUPPORT=ON
          just build_core_experimental AVX512_SUPPORT=ON

      - name: Build Release boolean
        run: |
          just build_boolean

      - name: Build Release shortint
        run: |
          just build_shortint

      - name: Build Release integer
        run: |
          just build_integer

      - name: Build Release tfhe full
        run: |
          just build_tfhe_full

      - name: Build Release c_api
        run: |
          just build_c_api

      # The wasm build check is a bit annoying to set-up here and is done during the tests in
      # aws_tfhe_tests.yml
